-- =====================================================================
-- AI-Based Smart Governance and Compliance Monitoring System
-- Coal India Limited / Ministry of Coal - SIH 2026 (SIH26024)
-- Database Schema (PostgreSQL)
-- =====================================================================

BEGIN;

-- 1. ROLES
CREATE TABLE IF NOT EXISTS roles (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_key      VARCHAR(50) NOT NULL UNIQUE,
    role_name     VARCHAR(100) NOT NULL,
    description   VARCHAR(255),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. SUBSIDIARIES
CREATE TABLE IF NOT EXISTS subsidiaries (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150) NOT NULL,
    code          VARCHAR(20) NOT NULL UNIQUE,
    headquarters  VARCHAR(150),
    status        VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. USERS
CREATE TABLE IF NOT EXISTS users (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR(150) NOT NULL,
    email           VARCHAR(150) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    role_id         INT NOT NULL,
    subsidiary_id   INT NULL,
    phone           VARCHAR(20),
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE','SUSPENDED')),
    last_login_at   TIMESTAMPTZ NULL,
    created_by      INT NULL,
    updated_by      INT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT fk_users_subsidiary FOREIGN KEY (subsidiary_id) REFERENCES subsidiaries(id)
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role_id);

-- 4. MINES
CREATE TABLE IF NOT EXISTS mines (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mine_name           VARCHAR(150) NOT NULL,
    mine_code           VARCHAR(30) NOT NULL UNIQUE,
    subsidiary_id       INT NOT NULL,
    state               VARCHAR(100),
    district            VARCHAR(100),
    latitude            DECIMAL(10,6),
    longitude           DECIMAL(10,6),
    mine_type           VARCHAR(20) NOT NULL DEFAULT 'OPENCAST' CHECK (mine_type IN ('OPENCAST','UNDERGROUND','MIXED')),
    production_capacity DECIMAL(12,2),
    manager_id          INT NULL,
    status              VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE','UNDER_MAINTENANCE')),
    created_by          INT NULL,
    updated_by          INT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_mines_subsidiary FOREIGN KEY (subsidiary_id) REFERENCES subsidiaries(id),
    CONSTRAINT fk_mines_manager FOREIGN KEY (manager_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_mines_subsidiary ON mines(subsidiary_id);
CREATE INDEX IF NOT EXISTS idx_mines_status ON mines(status);

-- 5. MINE ZONES
CREATE TABLE IF NOT EXISTS mine_zones (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mine_id     INT NOT NULL,
    zone_name   VARCHAR(100) NOT NULL,
    zone_type   VARCHAR(100),
    latitude    DECIMAL(10,6),
    longitude   DECIMAL(10,6),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_mine_zones_mine FOREIGN KEY (mine_id) REFERENCES mines(id) ON DELETE CASCADE
);

-- 6. DEPARTMENTS
CREATE TABLE IF NOT EXISTS departments (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mine_id     INT NOT NULL,
    dept_name   VARCHAR(100) NOT NULL,
    dept_head_id INT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_departments_mine FOREIGN KEY (mine_id) REFERENCES mines(id) ON DELETE CASCADE,
    CONSTRAINT fk_departments_head FOREIGN KEY (dept_head_id) REFERENCES users(id)
);

-- 7. CONTRACTORS
CREATE TABLE IF NOT EXISTS contractors (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mine_id         INT NOT NULL,
    company_name    VARCHAR(150) NOT NULL,
    contact_person  VARCHAR(150),
    phone           VARCHAR(20),
    email           VARCHAR(150),
    contract_type   VARCHAR(100),
    contract_start  DATE,
    contract_end    DATE,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE','BLACKLISTED')),
    blacklist_reason TEXT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_contractors_mine FOREIGN KEY (mine_id) REFERENCES mines(id) ON DELETE CASCADE
);

-- 8. WORKERS
CREATE TABLE IF NOT EXISTS workers (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mine_id         INT NOT NULL,
    worker_code     VARCHAR(30) NOT NULL UNIQUE,
    full_name       VARCHAR(150) NOT NULL,
    designation     VARCHAR(100),
    department_id   INT NULL,
    contractor_id   INT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_workers_mine FOREIGN KEY (mine_id) REFERENCES mines(id) ON DELETE CASCADE,
    CONSTRAINT fk_workers_department FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_workers_contractor FOREIGN KEY (contractor_id) REFERENCES contractors(id)
);

-- 9. COMPLIANCE CATEGORIES
CREATE TABLE IF NOT EXISTS compliance_categories (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255)
);

-- 10. COMPLIANCE RULES
CREATE TABLE IF NOT EXISTS compliance_rules (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code           VARCHAR(30) NOT NULL UNIQUE,
    title               VARCHAR(200) NOT NULL,
    description         TEXT,
    category_id         INT NOT NULL,
    applicable_mine_id  INT NULL,
    frequency           VARCHAR(20) NOT NULL DEFAULT 'MONTHLY' CHECK (frequency IN ('DAILY','WEEKLY','MONTHLY','QUARTERLY','ANNUAL','ONE_TIME')),
    severity            VARCHAR(20) NOT NULL DEFAULT 'MEDIUM' CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    responsible_dept    VARCHAR(100),
    due_period_days     INT DEFAULT 30,
    status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
    created_by          INT NULL,
    updated_by          INT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_compliance_rules_category FOREIGN KEY (category_id) REFERENCES compliance_categories(id),
    CONSTRAINT fk_compliance_rules_mine FOREIGN KEY (applicable_mine_id) REFERENCES mines(id)
);

-- 11. INSPECTIONS
CREATE TABLE IF NOT EXISTS inspections (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mine_id             INT NOT NULL,
    inspection_type     VARCHAR(100),
    inspector_id        INT NOT NULL,
    inspection_date     DATE NOT NULL,
    inspection_time     TIME,
    gps_latitude        DECIMAL(10,6),
    gps_longitude       DECIMAL(10,6),
    remarks             TEXT,
    status              VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','SUBMITTED','REVIEWED','APPROVED')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_inspections_mine FOREIGN KEY (mine_id) REFERENCES mines(id),
    CONSTRAINT fk_inspections_inspector FOREIGN KEY (inspector_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_inspections_mine ON inspections(mine_id);
CREATE INDEX IF NOT EXISTS idx_inspections_date ON inspections(inspection_date);

-- 12. INSPECTION ITEMS
CREATE TABLE IF NOT EXISTS inspection_items (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspection_id   INT NOT NULL,
    checklist_item  VARCHAR(255) NOT NULL,
    result          VARCHAR(20) NOT NULL DEFAULT 'NA' CHECK (result IN ('PASS','FAIL','NA')),
    remarks         VARCHAR(255),
    CONSTRAINT fk_inspection_items_inspection FOREIGN KEY (inspection_id) REFERENCES inspections(id) ON DELETE CASCADE
);

-- 13. OBSERVATIONS
CREATE TABLE IF NOT EXISTS observations (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspection_id   INT NOT NULL,
    category_id     INT NULL,
    observation     TEXT NOT NULL,
    severity        VARCHAR(20) NOT NULL DEFAULT 'LOW' CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    evidence_path   VARCHAR(255),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_observations_inspection FOREIGN KEY (inspection_id) REFERENCES inspections(id) ON DELETE CASCADE,
    CONSTRAINT fk_observations_category FOREIGN KEY (category_id) REFERENCES compliance_categories(id)
);

-- 14. VIOLATIONS
CREATE TABLE IF NOT EXISTS violations (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    violation_code      VARCHAR(30) NOT NULL UNIQUE,
    mine_id             INT NOT NULL,
    inspection_id       INT NULL,
    category_id         INT NOT NULL,
    description         TEXT NOT NULL,
    severity            VARCHAR(20) NOT NULL DEFAULT 'MEDIUM' CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    evidence_path       VARCHAR(255),
    reported_by         INT NOT NULL,
    responsible_person  INT NULL,
    deadline            DATE,
    status              VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','IN_PROGRESS','RESOLVED','VERIFIED','CLOSED','OVERDUE')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_violations_mine FOREIGN KEY (mine_id) REFERENCES mines(id),
    CONSTRAINT fk_violations_inspection FOREIGN KEY (inspection_id) REFERENCES inspections(id),
    CONSTRAINT fk_violations_category FOREIGN KEY (category_id) REFERENCES compliance_categories(id),
    CONSTRAINT fk_violations_reported_by FOREIGN KEY (reported_by) REFERENCES users(id),
    CONSTRAINT fk_violations_responsible FOREIGN KEY (responsible_person) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_violations_mine ON violations(mine_id);
CREATE INDEX IF NOT EXISTS idx_violations_status ON violations(status);

-- 15. CORRECTIVE ACTIONS
CREATE TABLE IF NOT EXISTS corrective_actions (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    violation_id        INT NOT NULL,
    assigned_to         INT NOT NULL,
    action_description  TEXT NOT NULL,
    deadline            DATE NOT NULL,
    submitted_at        TIMESTAMPTZ NULL,
    verified_by         INT NULL,
    verified_at         TIMESTAMPTZ NULL,
    escalation_level    INT DEFAULT 0,
    status              VARCHAR(20) NOT NULL DEFAULT 'ASSIGNED' CHECK (status IN ('ASSIGNED','SUBMITTED','VERIFIED','CLOSED','OVERDUE')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_corrective_actions_violation FOREIGN KEY (violation_id) REFERENCES violations(id),
    CONSTRAINT fk_corrective_actions_assignee FOREIGN KEY (assigned_to) REFERENCES users(id),
    CONSTRAINT fk_corrective_actions_verifier FOREIGN KEY (verified_by) REFERENCES users(id)
);

-- 16. INCIDENTS
CREATE TABLE IF NOT EXISTS incidents (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mine_id         INT NOT NULL,
    incident_type   VARCHAR(100),
    description     TEXT,
    severity        VARCHAR(20) NOT NULL DEFAULT 'MEDIUM' CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    reported_by     INT NOT NULL,
    incident_date   TIMESTAMPTZ NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','UNDER_REVIEW','CLOSED')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_incidents_mine FOREIGN KEY (mine_id) REFERENCES mines(id),
    CONSTRAINT fk_incidents_reported_by FOREIGN KEY (reported_by) REFERENCES users(id)
);

-- 17. OPERATIONAL DATA
CREATE TABLE IF NOT EXISTS operational_data (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mine_id             INT NOT NULL,
    record_date         DATE NOT NULL,
    production_tonnes   DECIMAL(12,2),
    expected_production DECIMAL(12,2),
    equipment_health_pct DECIMAL(5,2),
    attendance_pct      DECIMAL(5,2),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_operational_data_mine FOREIGN KEY (mine_id) REFERENCES mines(id)
);

CREATE INDEX IF NOT EXISTS idx_opdata_mine_date ON operational_data(mine_id, record_date);

-- 18. ENVIRONMENTAL DATA
CREATE TABLE IF NOT EXISTS environmental_data (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mine_id             INT NOT NULL,
    record_date         DATE NOT NULL,
    aqi                 DECIMAL(6,2),
    water_quality_index DECIMAL(6,2),
    noise_level_db      DECIMAL(6,2),
    dust_level          DECIMAL(6,2),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_environmental_data_mine FOREIGN KEY (mine_id) REFERENCES mines(id)
);

-- 19. ATTENDANCE
CREATE TABLE IF NOT EXISTS attendance (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mine_id         INT NOT NULL,
    worker_id       INT NULL,
    record_date     DATE NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'PRESENT' CHECK (status IN ('PRESENT','ABSENT','LEAVE','HALF_DAY')),
    shift           VARCHAR(20) DEFAULT 'GENERAL',
    overtime_hours  DECIMAL(4,2) DEFAULT 0.00,
    present_count   INT NULL,
    total_count     INT NULL,
    marked_by       INT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_attendance_mine FOREIGN KEY (mine_id) REFERENCES mines(id),
    CONSTRAINT fk_attendance_worker FOREIGN KEY (worker_id) REFERENCES workers(id),
    CONSTRAINT fk_attendance_marked_by FOREIGN KEY (marked_by) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_attendance_mine_date ON attendance(mine_id, record_date);
CREATE INDEX IF NOT EXISTS idx_attendance_worker ON attendance(worker_id);

-- 20. DOCUMENTS
CREATE TABLE IF NOT EXISTS documents (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mine_id             INT NULL,
    contractor_id       INT NULL,
    document_type       VARCHAR(100),
    file_path           VARCHAR(255) NOT NULL,
    certificate_number  VARCHAR(100),
    issue_date          DATE,
    expiry_date         DATE,
    ocr_raw_text        TEXT,
    mine_code           VARCHAR(50) NULL,
    inspector_name      VARCHAR(100) NULL,
    inspection_date     DATE NULL,
    compliance_status   VARCHAR(50) DEFAULT 'COMPLIANT',
    violation_details   TEXT NULL,
    risk_level          VARCHAR(30) DEFAULT 'LOW',
    corrective_action   TEXT NULL,
    due_date            DATE NULL,
    regulatory_reference VARCHAR(255) NULL,
    ocr_data_json       JSONB,
    workflow_status     VARCHAR(50) DEFAULT 'PENDING_REVIEW',
    uploaded_by         INT NOT NULL,
    reviewed_by         INT NULL,
    reviewed_at         TIMESTAMPTZ NULL,
    approved_by         INT NULL,
    approved_at         TIMESTAMPTZ NULL,
    verified_by         INT NULL,
    verified_at         TIMESTAMPTZ NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'VALID' CHECK (status IN ('VALID','EXPIRING_SOON','EXPIRED')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_documents_mine FOREIGN KEY (mine_id) REFERENCES mines(id),
    CONSTRAINT fk_documents_contractor FOREIGN KEY (contractor_id) REFERENCES contractors(id),
    CONSTRAINT fk_documents_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(id),
    CONSTRAINT fk_documents_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id),
    CONSTRAINT fk_documents_approved_by FOREIGN KEY (approved_by) REFERENCES users(id),
    CONSTRAINT fk_documents_verified_by FOREIGN KEY (verified_by) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_documents_contractor ON documents(contractor_id);

-- 21. RISK SCORES
CREATE TABLE IF NOT EXISTS risk_scores (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mine_id         INT NOT NULL,
    score           DECIMAL(5,2) NOT NULL,
    classification   VARCHAR(20) NOT NULL CHECK (classification IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    factors_json    JSONB,
    computed_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_risk_scores_mine FOREIGN KEY (mine_id) REFERENCES mines(id)
);

CREATE INDEX IF NOT EXISTS idx_risk_mine ON risk_scores(mine_id);

-- 22. ANOMALIES
CREATE TABLE IF NOT EXISTS anomalies (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mine_id         INT NOT NULL,
    anomaly_type    VARCHAR(100),
    description     TEXT,
    detected_value  DECIMAL(12,2),
    expected_value  DECIMAL(12,2),
    severity        VARCHAR(20) NOT NULL DEFAULT 'MEDIUM' CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    status          VARCHAR(20) NOT NULL DEFAULT 'NEW' CHECK (status IN ('NEW','ACKNOWLEDGED','RESOLVED')),
    detected_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_anomalies_mine FOREIGN KEY (mine_id) REFERENCES mines(id)
);

-- 23. NOTIFICATIONS
CREATE TABLE IF NOT EXISTS notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id    INT NOT NULL,
    title           VARCHAR(200) NOT NULL,
    message         TEXT NOT NULL,
    severity        VARCHAR(20) NOT NULL DEFAULT 'INFO' CHECK (severity IN ('INFO','WARNING','CRITICAL')),
    type            VARCHAR(50),
    is_read         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_notif_recipient ON notifications(recipient_id, is_read);

-- 24. AUDIT LOGS (Hash-chained for tamper evidence)
CREATE TABLE IF NOT EXISTS audit_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INT NULL,
    action          VARCHAR(100) NOT NULL,
    module          VARCHAR(100),
    record_id       VARCHAR(50),
    details         JSONB,
    ip_address      VARCHAR(50),
    prev_hash       VARCHAR(64) NULL,
    hash            VARCHAR(64) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_module ON audit_logs(module);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at);

-- 25. GRIEVANCES
CREATE TABLE IF NOT EXISTS grievances (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id       INT NULL,
    mine_id         INT NOT NULL,
    category        VARCHAR(100) NOT NULL,
    description     TEXT NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED' CHECK (status IN ('SUBMITTED','IN_REVIEW','RESOLVED','ESCALATED','CLOSED')),
    assigned_to     INT NULL,
    resolution_notes TEXT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_grievances_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE SET NULL,
    CONSTRAINT fk_grievances_mine FOREIGN KEY (mine_id) REFERENCES mines(id) ON DELETE CASCADE,
    CONSTRAINT fk_grievances_assignee FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_grievances_mine ON grievances(mine_id);
CREATE INDEX IF NOT EXISTS idx_grievances_status ON grievances(status);

-- 26. REPORTS
CREATE TABLE IF NOT EXISTS reports (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type     VARCHAR(100) NOT NULL,
    generated_by    INT NOT NULL,
    mine_id         INT NULL,
    file_path       VARCHAR(255),
    format          VARCHAR(20) NOT NULL DEFAULT 'PDF' CHECK (format IN ('PDF','CSV')),
    parameters_json JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_reports_generated_by FOREIGN KEY (generated_by) REFERENCES users(id),
    CONSTRAINT fk_reports_mine FOREIGN KEY (mine_id) REFERENCES mines(id)
);

-- 27. AI INSPECTION ANALYSES
CREATE TABLE IF NOT EXISTS ai_inspection_analyses (
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspection_id      INT NOT NULL,
    category           VARCHAR(100),
    severity           VARCHAR(20) NOT NULL DEFAULT 'LOW' CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    risk_level         VARCHAR(20) NOT NULL DEFAULT 'LOW' CHECK (risk_level IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    risk_score         INT NOT NULL,
    summary            TEXT,
    reasoning          TEXT,
    recommended_action TEXT,
    recurring_issue    BOOLEAN NOT NULL DEFAULT FALSE,
    urgency            VARCHAR(50),
    confidence         DECIMAL(5,2),
    model_name         VARCHAR(100),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ai_inspection_analyses_inspection FOREIGN KEY (inspection_id) REFERENCES inspections(id) ON DELETE CASCADE
);

COMMIT;
